authenticate/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = "authenticate"

urlpatterns = [
    path('', views.home, name='home'),
    path('login/',auth_views.LoginView.as_view(template_name='authenticate/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='authenticate/logout.html'), name='logout'),
    path('register/', views.register_user, name='register'),
    path('change_password/', auth_views.PasswordChangeView.as_view(template_name='authenticate/change_password.html' , success_url=reverse_lazy('authenticate:password_change_done')), name='change_password'),
    path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(template_name='authenticate/password_change_done.html'),name='password_change_done'),
    
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html' , success_url=reverse_lazy('authenticate:password_reset_done')),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html' , success_url=reverse_lazy('authenticate:password_reset_complete')), name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('poll_list.urls', namespace="poll")),
    path('', include('authenticate.urls', namespace="authenticate")),
]

authenticate/models.py
from django.db import models

# Create your models here.

authenticate/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm, PasswordResetForm
from django.contrib.auth.models import User
from django import forms


class SignUpForm(UserCreationForm):
    username = forms.CharField(label="",
                               max_length=32, help_text="<small id='emailHelp' class='form-text text-muted'>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small>", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}))
    first_name = forms.CharField(label="",
                                 max_length=32, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'}))
    last_name = forms.CharField(label="",
                                max_length=32, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}))
    email = forms.EmailField(label="",
                             max_length=50, widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}))
    password1 = forms.CharField(label="", help_text="<small><ul class='form-text text-muted'><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul></small>",
                                max_length=40, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))
    password2 = forms.CharField(label="", help_text="<small class='form-text text-muted'>Enter the same password as before, for verification.</small>",
                                max_length=40, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm Password'}))

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name',
                  'email', 'password1', 'password2']

authenticate/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate , login
from .forms import SignUpForm
from django.contrib.auth.models import User


def home(request):
    return render(request, 'authenticate/home.html')


def register_user(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(request, username=username, password=password)
            login(request, user)
            return redirect('authenticate:home')
        else:
            form = SignUpForm(request.POST)
    else:
        form = SignUpForm()
    context = {
        'form': form,
    }
    return render(request, 'authenticate/register.html', context)

authenticate/templates/authenticate/change_password.html
{% extends 'base.html' %}

{% block content %}
<div class="text-center mt-4 mb-4">
    <h2 class="text-muted">Change Password</h2>
</div>
<div class="col-md-6 offset-md-3 mb-4">
    <form action="{% url 'authenticate:change_password' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-secondary">Change</button>
    </form>
</div>
{% endblock content %}

authenticate/templates/authenticate/edit_profile.html
{% extends 'base.html' %}

{% block content %}
<div class="text-center mt-4 mb-4">
    <h2 class="text-muted">Edit Profile</h2>
</div>
<div class="col-md-6 offset-md-3 mb-4">
    <form action="{% url 'edit_profile' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-secondary mb-3">Update</button>
        <p><a href="{% url 'change_password' %}">Click Here</a> To Change Your Password </p>
    </form>
</div>
{% endblock content %}

authenticate/templates/authenticate/home.html
{% extends 'base.html' %}

{% block content %}

{% if messages %}
{% for message in messages %}
<div class="alert alert-success alert-dismissible fade show mt-4" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
    </button>
    {{ message }}
</div>
{% endfor %}
{% endif %}

<div class="col-md-6 offset-md-3">

    {% if request.user.is_authenticated %}
    <h1 class="text-muted text-center mt-3 mb-3">User Information</h1>
    <ul class="list-group">
        <li class="list-group-item"><b>Name:</b> {{ user.first_name }} {{ user.last_name }}</li>
        <li class="list-group-item"><b>Username:</b> {{ user.username }}</li>
        <li class="list-group-item"><b>Email:</b> {{ user.email }}</li>
    </ul>
    {% else %}
    <h1 class="text-muted text-center mt-5 mb-5">Welcome to User Authentication App</h1>
    <h2 class="text-muted text-center mt-5">Login to see user information</h2>
    {% endif %}
</div>
{% endblock content %}

authenticate/templates/authenticate/login.html
{% extends 'base.html' %}

{% block content %}
<div class="text-center mt-4 text-muted">
    <h2>User Login</h2>
</div>
<div class="col-md-6 offset-md-3">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">Close</span>
        </button>
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    <form action="{% url 'authenticate:login' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Username:</label>
            <input type="text" class="form-control" name="username" id="username" placeholder="Enter Password">
        </div>
        <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" class="form-control" name="password" id="password" placeholder="Enter Password">
        </div>
        <button type="submit" class="btn btn-secondary mb-3">Login</button>
        <p>Forgot password ??<a href="{% url 'authenticate:password_reset' %}"> Click Here</a> To Reset</p>
    </form>
</div>
{% endblock content %}

authenticate/templates/authenticate/password_change_done.html
{% extends 'base.html' %}

{% block content %}
<div class="text-center mt-4 text-muted">
    <h2>Password Change Succesfully</h2>
</div>

        <p>
            please login again
        </p>
    

{% endblock content %}

authenticate/templates/authenticate/register.html
{% extends 'base.html' %}

{% block content %}
<div class="text-center mt-4 mb-4">
    <h2 class="text-muted">Register</h2>
</div>
<div class="col-md-6 offset-md-3 mb-4">
    <form action="{% url 'authenticate:register' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-secondary">Register</button>
    </form>
</div>
{% endblock content %}