authenticate/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = "authenticate"

urlpatterns = [
    path('', views.home, name='home'),
    path('login/',auth_views.LoginView.as_view(template_name='authenticate/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='authenticate/logout.html'), name='logout'),
    path('register/', views.register_user, name='register'),
    path('change_password/', auth_views.PasswordChangeView.as_view(template_name='authenticate/change_password.html' , success_url=reverse_lazy('authenticate:password_change_done')), name='change_password'),
    path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(template_name='authenticate/password_change_done.html'),name='password_change_done'),
    
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html' , success_url=reverse_lazy('authenticate:password_reset_done')),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html' , success_url=reverse_lazy('authenticate:password_reset_complete')), name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('poll_list.urls', namespace="poll")),
    path('', include('authenticate.urls', namespace="authenticate")),
]

poll_list/urls.py
from django.urls import path 
from .import views
app_name = 'poll'
urlpatterns = [
    path('', views.HomeView.as_view() , name="home"),
    path('poll-list', views.PollView.as_view() , name = "poll"),
    path('poll-list/<str:username>', views.MyPollView.as_view() , name = "mypoll"),
    path('add-Poll', views.AddPollView.as_view() , name = "addpoll"),
    path('Poll-end/<int:id>', views.PollEndView.as_view() , name = "pollend"),
    path('edit-poll/<int:id>', views.EditPollView.as_view() , name = "editpoll"),
    path('delete-poll/<int:id>', views.DeletePollView.as_view() , name = "deletepoll"),
    path('add-choice/<int:id>', views.AddChoiceView.as_view() , name = "addchoice"),
    path('edit-choice/<int:id>/<int:cid>', views.EditChoiceView.as_view() , name = "editchoice"),
    path('delete-choice/<int:id>/<int:cid>', views.DeleteChoiceView.as_view() , name = "deletechoice"),
    path('<int:id>', views.PollDetailsView.as_view() , name = "polldetails"),
    path('Result/<int:id>', views.ResultView.as_view() , name = "result"),

]

templates/includes/navbar.html
{% load static %}
<nav class="navbar navbar-expand-sm navbar-light bg-light">
    <a class="navbar-brand" href=""><img src="{% static 'img/logo.jpg' %}" width="50px"></a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
        aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'poll:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'poll:poll' %}">Poll List</a>
            </li>
        </ul>
        <div class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
            <a class="nav-link" href="{% url 'poll:mypoll' username=user.username %}">My Poll List</a>
            <a class="nav-link" href="{% url 'authenticate:logout' %}">Logout</a>
            {% else %}
            <a class="nav-link" href="{% url 'authenticate:login' %}">Login</a>
            <a class="nav-link" href="{% url 'authenticate:register' %}">Register</a>
            {% endif %}
        </div>
    </div>
</nav>