myproject/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('poll_list.urls', namespace="poll")),
    path('', include('authenticate.urls', namespace="authenticate")),
]

poll_list/urls.py
from django.urls import path 
from .import views
app_name = 'poll'
urlpatterns = [
    path('', views.HomeView.as_view() , name="home"),
    path('poll-list', views.PollView.as_view() , name = "poll"),
    path('poll-list/<str:username>', views.MyPollView.as_view() , name = "mypoll"),
    path('add-Poll', views.AddPollView.as_view() , name = "addpoll"),
    path('Poll-end/<int:id>', views.PollEndView.as_view() , name = "pollend"),
    path('edit-poll/<int:id>', views.EditPollView.as_view() , name = "editpoll"),
    path('delete-poll/<int:id>', views.DeletePollView.as_view() , name = "deletepoll"),
    path('add-choice/<int:id>', views.AddChoiceView.as_view() , name = "addchoice"),
    path('edit-choice/<int:id>/<int:cid>', views.EditChoiceView.as_view() , name = "editchoice"),
    path('delete-choice/<int:id>/<int:cid>', views.DeleteChoiceView.as_view() , name = "deletechoice"),
    path('<int:id>', views.PollDetailsView.as_view() , name = "polldetails"),
    path('Result/<int:id>', views.ResultView.as_view() , name = "result"),

]

poll_list/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.
class Poll(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.TextField()
    pub_date = models.DateTimeField(default=timezone.now)
    active = models.BooleanField(default=True)

    def user_can_vote(self, user):
        """ 
        Return False if user already voted
        """
        user_votes = user.vote_set.all()
        qs = user_votes.filter(poll=self)
        if qs.exists():
            return False
        return True

    def __str__(self):
        return self.subject

class Choice(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE,related_name='choises')
    choice_option = models.CharField(max_length=50)

    def __str__(self):
        return str(self.poll)+'--' + str(self.choice_option)

class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE , related_name="votes")

    def __str__(self):
        return str(self.choice) +'--' + str(self.user)

poll_list/forms.py
from django import forms
from .models import Poll,Choice

class AddPollForm(forms.ModelForm):
    class Meta:
        model = Poll
        fields = [
            'subject',
        ]
class AddChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = [
            'choice_option',
        ]

class SearchForm(forms.Form):
    search = forms.CharField(required=False)

poll_list/views.py
from django.shortcuts import render , redirect , get_object_or_404
from .models import Poll , Choice ,Vote
from django.views import View, generic
from django.contrib.auth.models import User
from .forms import AddPollForm , AddChoiceForm , SearchForm
from authenticate.mixins import AictiveUserRequiredMixin
from django.contrib import messages
from django.db.models import Count
# Create your views here.

class HomeView(generic.TemplateView):
    template_name = 'home.html'

class PollView(AictiveUserRequiredMixin,generic.ListView):
    model = Poll
    paginate_by = 10
    context_object_name = 'polls'
    template_name = "polls/polls_list.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Poll List'
        context['form'] = SearchForm()
        return context
    def get_queryset(self):
        qs = Poll.objects.all()
        search = self.request.GET.get('search')
        if search:
            qs = Poll.objects.filter(subject__icontains=search)
        if 'name' in self.request.GET:
            qs = Poll.objects.all().order_by('subject')

        if 'date' in self.request.GET:
            qs = Poll.objects.all().order_by('-pub_date')

        if 'vote' in self.request.GET:
            qs = Poll.objects.all().annotate(Count('vote')).order_by('-vote__count')
        return qs

class MyPollView(generic.ListView):
    model = Poll
    paginate_by = 10
    context_object_name = 'polls'
    template_name = "polls/polls_list.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Poll List'
        return context
    def get_queryset(self):
        qs = Poll.objects.filter(owner__username=self.request.resolver_match.kwargs['username']).all()
        return qs

class AddPollView(AictiveUserRequiredMixin,View):
    def get(self, request, *args, **kwargs):
        pollform = AddPollForm()
        choiceform = AddChoiceForm(prefix="choiceform")
        choiceform2 = AddChoiceForm(prefix="choiceform2")
        context = {
            'title': 'Add Poll',
            'pollform': pollform,
            'choiceform':choiceform,
            'choiceform2':choiceform2
        }
        return render(request, 'polls/add_poll.html', context)
    
    def post(self, request, *args, **kwargs):
        user = self.request.user
        pollform = AddPollForm(request.POST or None)
        choiceform = AddChoiceForm(request.POST or None ,prefix="choiceform")
        choiceform2 = AddChoiceForm(request.POST or None ,prefix="choiceform2")
        if pollform.is_valid():
            instance = pollform.save(commit=False)
            instance.owner = user
            instance.save()
            poll = Poll.objects.last()

            if choiceform.is_valid() and choiceform2.is_valid():
                instance = choiceform.save(commit=False)
                instance.poll = poll
                instance.save()
            
                instance = choiceform2.save(commit=False)
                instance.poll = poll
                instance.save()
                return redirect('poll:poll')
    

class PollEndView(View):
    def get(self, request, *args, **kwargs):
        poll = get_object_or_404(Poll, id=self.request.resolver_match.kwargs['id'])
        if poll.active:
            poll.active = False
            poll.save()
        return redirect('poll:poll')

class EditPollView(View):
    def get(self, request, *args, **kwargs):
        poll = get_object_or_404(Poll, id=self.request.resolver_match.kwargs['id'])
        form = AddPollForm(instance=poll)
        return render(request, 'polls/poll_edit.html', {'form': form , 'poll':poll})

    def post(self, request, *args, **kwargs):
        poll = get_object_or_404(Poll, id=self.request.resolver_match.kwargs['id'])
        form = AddPollForm(instance=poll)
        if request.method == 'POST':
            form = AddPollForm(request.POST or None, instance=poll)
            if form.is_valid():
                form.save()
                return redirect('poll:poll')

class DeletePollView(View):
    def get(self, request, *args, **kwargs):
        poll = get_object_or_404(Poll, id=self.request.resolver_match.kwargs['id'])
        instance = poll
        instance.delete()
        return redirect('poll:poll')
        
class AddChoiceView(View):
    def get(self, request, *args, **kwargs):
        poll = get_object_or_404(Poll, id=self.request.resolver_match.kwargs['id'])
        choiceform = AddChoiceForm()
        context = {
            'choiceform':choiceform,
            'poll':poll
        }
        return render(request, 'polls/add_choice.html', context)
    
    def post(self, request, *args, **kwargs):
        choiceform = AddChoiceForm(request.POST or None )
        poll = get_object_or_404(Poll, id=self.request.resolver_match.kwargs['id'])
        if choiceform.is_valid():
            instance = choiceform.save(commit=False)
            instance.poll = poll
            instance.save()
            return redirect('poll:poll')

class EditChoiceView(View):
    def get(self, request, *args, **kwargs):
        poll = get_object_or_404(Poll, id=self.request.resolver_match.kwargs['id'])
        choice = get_object_or_404(Choice , id = self.request.resolver_match.kwargs['cid'])
        choiceform = AddChoiceForm(instance=choice)
        context = {
            'choiceform':choiceform,
            'poll':poll,
            'choice':choice
        }
        return render(request, 'polls/edit_choice.html', context)
    
    def post(self, request, *args, **kwargs):
        poll = get_object_or_404(Poll, id=self.request.resolver_match.kwargs['id'])
        choice = get_object_or_404(Choice , id = self.request.resolver_match.kwargs['cid'])
        choiceform = AddChoiceForm(request.POST or None,instance=choice )
        if choiceform.is_valid():
            instance = choiceform.save(commit=False)
            instance.poll = poll
            instance.save()
            return redirect('poll:poll')

class DeleteChoiceView(View):
    def get(self, request, *args, **kwargs):
        poll = get_object_or_404(Poll, id=self.request.resolver_match.kwargs['id'])
        choice = get_object_or_404(Choice , id = self.request.resolver_match.kwargs['cid'])
        instance = choice
        instance.delete()
        return redirect('poll:poll')

class PollDetailsView(View):
    def get(self, request, *args, **kwargs):
        poll = get_object_or_404(Poll, id=self.request.resolver_match.kwargs['id'])
        context = {
            'poll':poll,
        }
        return render(request, 'polls/poll_detail.html', context)
    def post(self, request, *args, **kwargs):
        poll = get_object_or_404(Poll, id=self.request.resolver_match.kwargs['id'])
        choice_id = request.POST.get('choice')
        if not poll.user_can_vote(request.user):
            messages.error(
                request, "You already voted this poll", extra_tags='alert alert-warning alert-dismissible fade show')
            return redirect("poll:poll")
        if choice_id:
            choice = Choice.objects.get(id=choice_id)
            vote = Vote(user=request.user, poll=poll, choice=choice)
            vote.save()
            return redirect('poll:result',id=poll.id)


class ResultView(View):
    def get(self, request, *args, **kwargs):
        poll = get_object_or_404(Poll, id=self.request.resolver_match.kwargs['id'])
        vot = Vote.objects.filter(poll__id=self.request.resolver_match.kwargs['id'])
        vote_count = Vote.objects.filter(poll__id=self.request.resolver_match.kwargs['id']).count()
        choice = Choice.objects.filter(poll__id=self.request.resolver_match.kwargs['id'])
        
        context = {
            'poll':poll,
            'vot':vot,
            'vote_count':vote_count,
            'choice':choice
        }
        return render(request , "polls/poll_result.html",context)

poll_list/templates/polls/add_choice.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row center">
        <div class="col-md-6 offset-md-3">
            {% if edit_choice %}
            <h2>Update choice</h2>
            {% else %}
            <h2>Add new choice</h2>
            {% endif %}
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            <form action="" method="POST">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    {{ field }}
                </div>
                {% endfor %}
                {% if edit_choice %}
                <button type="submit" class="btn btn-primary">Update</button>
                <a class="btn btn-danger" href="{% url 'polls:choice_delete' choice.id %}" role="button" onclick="return confirm('Are you sure you want to delete this?')">Delete</a>
                {% else %}
                <button type="submit" class="btn btn-primary">Add</button>
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

poll_list/templates/polls/add_poll.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row center">
        <div class="col-md-6 offset-md-3">
            <h2>Create new poll</h2>
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            <form action="" method="POST">
                {% csrf_token %}
                
                <div class="form-group">
                    {{ pollform.as_p }}
                    {{ choiceform.as_p }}
                    {{ choiceform2.as_p }}
                </div>
                
                <button type="submit" class="btn btn-primary">Add Poll</button>
                <a class="btn btn-warning" href="{% url 'poll:poll' %}" role="button">Back</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

poll_list/templates/polls/edit_choice.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row center">
        <div class="col-md-6 offset-md-3">
            <h2>Add new choice</h2>
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}

            <form action="" method="POST">
                {% csrf_token %} 
                <div class="form-group">
                   {{choiceform.as_p}}
                </div>          
                <button type="submit" class="btn btn-primary">Update</button>
                <a class="btn btn-danger" href="{% url 'poll:deletechoice' id=poll.id  cid=choice.id %}" role="button" onclick="return confirm('Are you sure you want to delete this?')">Delete</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

poll_list/templates/polls/endpoll.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <div class="row">
        <div class="col-md-8 offset-sm-2">
            <h3 class="mt-3 mb-3 text-center">Result for: {{ poll.text }}</h3>
            <!-- progress bar -->
    <div class="progress mt-3">

        {% for choice in poll.get_result_dict %}
        <div class="progress-bar bg-{{ choice.alert_class }}" role="progressbar" style="width: {{ choice.percentage }}%;" aria-valuenow="30" aria-valuemin="0"
            aria-valuemax="100"><b>{{ choice.text }}-{{ choice.percentage|floatformat }}%</b></div>
        {% endfor %}

    </div>
            <ul class="list-group">
                {% for choice in poll.choice_set.all %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    {{ choice.choice_text }}
                    <span class="badge badge-primary badge-pill">{{ choice.get_vote_count }}</span>
                </li>
                {% endfor %}
            </ul>
            {% endif %}
            <a class="btn btn-primary mt-3" href="{% url 'polls:list' %}" role="button">Back To Polls</a>
        </div>
        
    </div>
</div>
{% endblock content %}

poll_list/templates/polls/poll_detail.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
    <h1>Polls details page</h1>
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
    </div>
    {% endif %}
    <hr>
    <h2 class="mt-3 mb-3">{{ poll.subject }}</h2>
    <form action="" method="POST">
        {% csrf_token %}
        {% for cho in poll.choises.all %}
        <input type="radio" name="choice"  value="{{ cho.id }}">
        <label >{{ cho.choice_option }}</label>
        <br>
        {% endfor %}
        <input type="submit" value="Vote" class="btn btn-primary mt-3">
        <a class="btn btn-warning mt-3" href="{% url 'poll:poll' %}" role="button">Cancel</a>
    </form>

</div>

{% endblock content %}

poll_list/templates/polls/poll_edit.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row center">
        <div class="col-md-6 offset-md-3">
            <h2>Edit poll</h2>
            {% if messages %}
            {% if messages %}
            <div class="messages">
                {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %}
            </div>
            {% endif %}
            {% endif %}
            <form action="" method="POST">
                {% csrf_token %}
                
                <div class="form-group">
                    {{form.as_p}}
                </div>
                
                <button type="submit" class="btn btn-primary">Update</button>
                <a class="btn btn-danger" href="{% url 'poll:deletepoll' id=poll.id %}" role="button" onclick="return confirm('Are you sure?')">Delete</a>
                <a class="btn btn-warning" href="{% url 'poll:addchoice' id=poll.id %}" role="button">Add Choice</a>
            </form>

            <div class="choices">
                <h2 class="text-center mt-3">Choices</h2>
                <hr>
                <ul class="list-group">
                    {% comment %} {% for choice in poll.choice_set.all %} {% endcomment %}
                    {% comment %} {% for choice in poll.choise.all %} {% endcomment %}
                    {% for cho in poll.choises.all %}
                    <li class="list-group-item"><a href="{% url 'poll:editchoice' id=poll.id  cid=cho.id %}"><i class="fas fa-pencil-alt"></i></a>&nbsp
                        {{ cho.choice_option }}</li>
                    {% endfor %}
                </ul>
            </div>

        </div>
    </div>
</div>
{% endblock %}

poll_list/templates/polls/poll_result.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <div class="row">
        <div class="col-md-8 offset-sm-2">
            {% if poll.active %}
            <h3 class="mt-3 mb-3 text-center">"{{ poll.subject }}"</h3>
            {% else %}
            <h3 class="mt-3 mb-3 text-center">"{{ poll.subject }}" Has Ended Polling !</h3>
            {% endif %}
            <h3 class="mb-2 text-center">Total: {{ vote_count }} votes</h3>
            <!-- progress bar -->
            <div class="progress mt-3 mb-2">
                {% for choice in poll.get_result_dict %}
                <div class="progress-bar bg-{{ choice.alert_class }}" role="progressbar" style="width: {{ choice.percentage }}%;"
                    aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"><b>
                        {{choice.text|truncatewords:2}}-{{choice.percentage|floatformat}}%</b>
                </div>
                {% endfor %}

            </div>
            <ul class="list-group">
            
                {% for cho in choice %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    {{ cho.choice_option }}
                    <span class="badge badge-primary badge-pill">{{ cho.votes.count }}</span>
                </li>
                {% endfor %}
            </ul>
            {% endif %}
            <a class="btn btn-primary mt-3" href="{% url 'poll:poll' %}" role="button">Back To Polls</a>
        </div>

    </div>
</div>
{% endblock content %}

poll_list/templates/polls/polls_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-sm-2">
            <h1 class="text-center mt-3 mb-3">Welcome to polls List!</h1>
            {% if messages %}
            <div class="messages">
                {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %}
            </div>
            {% endif %}

            <a class="btn btn-{% if 'name' in request.GET %}warning{% else %}primary{% endif %} mb-3" href="?name=True"
                role="button"><i class="fas fa-sort-alpha-down"></i>
                Name</a>
            <a class="btn btn-{% if 'date' in request.GET %}warning{% else %}primary{% endif %} mb-3" href="?date=True"
                role="button"><i class="far fa-clock"></i> Date</a>
            <a class="btn btn-{% if 'vote' in request.GET %}warning{% else %}primary{% endif %} mb-3" href="?vote=True"
                role="button"><i class="fas fa-poll"></i> Vote</a> 

            <a class="btn btn-primary mb-3 float-right" href="{% url 'poll:addpoll' %}" role="button">Add <i class="fas fa-plus"></i></a>

            <form class="form-inline" method="GET">
                <div class="form-group mr-sm-2 mb-2">
                    <input type="search" class="form-control" name="search" placeholder="Search" value="">
                </div>
                <button type="submit" class="btn btn-primary mb-2"><i class="fas fa-search"></i></button>
            </form>


            <ul class="list-group">
                {% for poll in polls %}
                <li class="list-group-item">
                    {% if poll.active%}
                        <a href="{% url 'poll:polldetails' id=poll.id %}">{{ poll.subject|truncatewords:6 }}  </a>
                    {% else %}
                        <a href="{% url 'poll:result' id=poll.id %}">{{ poll.subject|truncatewords:6 }}  </a>
                        <i class="fas fa-check-circle ml-5 mr-2"></i>Vote End
                    {% endif %}
                    
                    <a href="{% url 'poll:result' id=poll.id %}" class="mr-3 ml-3 float-right btn btn-primary btn-sm" style="margin-top: -4px;" data-toggle="tooltip" data-placement="top"
                        title="Edit Poll">Result</a>
                    {% if request.user == poll.owner %}
                    {% if poll.active %}
                    <a href="{% url 'poll:pollend' id=poll.id %}" data-toggle="tooltip" data-placement="top" title="End Poll"
                        onclick="return confirm('Are you sure ?')"><i class="fas fa-step-forward float-right btn btn-danger btn-sm"></i></a>
                    {% endif %}
                    <a href="{% url 'poll:editpoll' id=poll.id %}" class="mr-3" data-toggle="tooltip" data-placement="top"
                        title="Edit Poll"><i class="fas fa-pencil-alt float-right btn btn-primary btn-sm mr-1"></i></a>
                    {% endif %}
                </li>

                {% endfor %}
            </ul>
            <nav class="mt-3">
                <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}"><i class="fas fa-angle-double-left"></i></a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="javascript:void(0)"><i class="fas fa-angle-double-left"></i></a></li>
                {% endif %}

                {% for i in page_obj.paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li class="page-item active"><a class="page-link" href="?page={{ i }}">{{i}}</a></li>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}"><i class="fas fa-angle-double-right"></i></a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="javascript:void(0)"><i class="fas fa-angle-double-right"></i></a></li>
                {% endif %}
            </ul>
            </nav> 
        </div>
    </div>
</div>

{% endblock content %}